name: test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  get: ^4.6.6
  shared_preferences: ^2.0.0
  socket_io_client: ^3.0.2
  intl: ^0.20.1
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  permission_handler: ^10.2.0
  path_provider: ^2.1.5
  mime: ^2.0.0
  http_parser: ^4.0.2
  flutter_sticky_header: ^0.7.0
  cached_network_image: ^3.3.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.0     # 用于处理经纬度

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: UnifrakturMaguntia
      fonts:
        - asset: assets/fonts/UnifrakturMaguntia-Regular.ttf
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
